<!DOCTYPE html>
<html lang="../fr"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-4a990d8dcb58f517c7c86712b8f2ac7c.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="A.Guilmain">
  <meta name="author" content="I.Balde">
  <meta name="author" content="A.Sylla">
  <meta name="author" content="D.Adjenia">
  <meta name="dcterms.date" content="2026-01-16">
  <title>La Courbe Environnementale de Kuznets</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-dbf1e3403c9b895633c92e3639c78a64.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">La Courbe Environnementale de Kuznets</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
A.Guilmain 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
I.Balde 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
A.Sylla 
</div>
</div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
D.Adjenia 
</div>
</div>
</div>

  <p class="date">2026-01-16</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Contenu</h2>
<ul>
<li><a href="#/la-courbe-environnementale-de-kuznets-pour-le-co₂" id="/toc-la-courbe-environnementale-de-kuznets-pour-le-co₂">La Courbe Environnementale de Kuznets pour le CO₂</a></li>
<li><a href="#/méthodologie" id="/toc-méthodologie">Méthodologie</a></li>
<li><a href="#/approche-transversale-1" id="/toc-approche-transversale-1">Approche Transversale</a></li>
<li><a href="#/approche-temporelle-1" id="/toc-approche-temporelle-1">Approche Temporelle</a></li>
<li><a href="#/confrontation-et-conclusion" id="/toc-confrontation-et-conclusion">Confrontation et Conclusion</a></li>
<li><a href="#/merci" id="/toc-merci">Merci</a></li>
<li><a href="#/annexes" id="/toc-annexes">Annexes</a></li>
</ul>
</nav>
</section>
<section>
<section id="la-courbe-environnementale-de-kuznets-pour-le-co₂" class="title-slide slide level1 center" data-background-image="../../artifacts/figures/trajectories_by_group.svg" data-background-opacity="0.2">
<h1>La Courbe Environnementale de Kuznets pour le CO₂</h1>

</section>
<section id="une-évaluation-empirique-par-approches-transversale-et-temporelle" class="slide level2 center">
<h2>Une évaluation empirique par approches transversale et temporelle</h2>
</section>
<section id="la-question-au-cœur-du-débat-climat" class="slide level2 center">
<h2>🎯 La question au cœur du débat climat</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Question de recherche</strong></p>
</div>
<div class="callout-content">
<blockquote>
<p><strong>« La croissance économique finit-elle par réduire la pollution ? »</strong></p>
</blockquote>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>L’hypothèse EKC</strong></p>
<ul>
<li>Relation en <strong>U inversé</strong> entre richesse et émissions</li>
<li>Phase 1 : Industrialisation → ↗️ pollution</li>
<li>Phase 2 : Services + tech → ↘️ pollution</li>
<li>Débat depuis <strong>30 ans</strong> sans consensus</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Notre approche originale</strong></p>
<p>✅ <strong>Double validation empirique</strong></p>
<ul>
<li>🌍 Espace : 159 pays en 2020</li>
<li>📈 Temps : USA 1990-2020</li>
</ul>
<p>✅ <strong>Double objectif</strong></p>
<ul>
<li>🔍 Estimer la forme</li>
<li>🎯 Prédire le futur</li>
</ul>
</div></div>
<aside class="notes">
<p>L’EKC est née en 1991. Elle a été utilisée pour justifier l’inaction climatique (“la croissance résoudra le problème”). Nous testons si cette promesse tient empiriquement.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="données-mobilisées" class="slide level2 center">
<h2>📊 Données mobilisées</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>Source et périmètre</strong></p>
<ul>
<li>📦 <strong>Our World in Data</strong> (OWID)
<ul>
<li>Global Carbon Project</li>
<li>Banque Mondiale</li>
</ul></li>
<li>📅 <strong>Période</strong> : 1990-2020 (30 ans)</li>
<li>🌍 <strong>Échantillon</strong> : 159 pays</li>
<li>📈 <strong>Observations</strong> : ~4770 lignes</li>
</ul>
</div><div class="column" style="width:55%;">
<p><strong>Variables retenues</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Unité</th>
<th>Justification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>CO₂/hab</strong></td>
<td>tonnes/an</td>
<td>Empreinte carbone territoriale</td>
</tr>
<tr class="even">
<td><strong>PIB/hab</strong></td>
<td>$ PPA 2017</td>
<td>Comparabilité internationale</td>
</tr>
</tbody>
</table>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Limite assumée</strong></p>
</div>
<div class="callout-content">
<p><strong>Émissions territoriales</strong> uniquement</p>
<p>→ Biais du <em>pollution haven</em> possible (délocalisation de la production polluante)</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="trajectoires-des-pays-par-groupe-de-revenu" class="slide level2 center">
<h2>🗺️ Trajectoires des pays par groupe de revenu</h2>

<img data-src="../../artifacts/figures/trajectories_by_group.svg" class="r-stretch quarto-figure-center"><p class="caption">Évolution des émissions par groupe (1990-2020)</p><aside class="notes">
<p>Ce graphique montre l’hétérogénéité des trajectoires : les pays riches ont amorcé leur déclin, les émergents sont en croissance exponentielle, les pays pauvres stagnent.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stratégie-empirique-double-approche" class="slide level2 center">
<h2>🎯 Stratégie empirique : Double approche</h2>
<div style="font-size: 0.85em;">
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 38%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>📸 Transversale</th>
<th>🎬 Temporelle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Échantillon</strong></td>
<td>159 pays</td>
<td>USA</td>
</tr>
<tr class="even">
<td><strong>Période</strong></td>
<td>2020 (photo)</td>
<td>1990-2020 (film)</td>
</tr>
<tr class="odd">
<td><strong>Question</strong></td>
<td>Les riches polluent-ils <strong>moins</strong> ?</td>
<td>Un pays se décarbone-t-il <strong>en s’enrichissant</strong> ?</td>
</tr>
<tr class="even">
<td><strong>Méthode</strong></td>
<td>OLS + validation croisée (k=5)</td>
<td>ARDL + test hors-échantillon</td>
</tr>
<tr class="odd">
<td><strong>Objectif</strong></td>
<td>Forme fonctionnelle</td>
<td>Dynamique temporelle</td>
</tr>
</tbody>
</table>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Triangulation méthodologique</strong></p>
</div>
<div class="callout-content">
<p>Si les deux approches <strong>convergent</strong> → robustesse structurelle</p>
<p>Si elles <strong>divergent</strong> → analyse de l’hétérogénéité spatiale vs inertie temporelle</p>
</div>
</div>
</div>
</section>
<section id="structure-de-la-présentation" class="slide level2 center">
<h2>📋 Structure de la présentation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Partie I : Méthodologie</strong></p>
<ul>
<li>Choix de spécification</li>
<li>Estimateurs utilisés</li>
<li>Protocoles de validation</li>
</ul>
<p><strong>Partie II : Approche transversale</strong></p>
<ul>
<li>Modèle quadratique vs cubique</li>
<li>Performance prédictive</li>
<li>Analyse des erreurs</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Partie III : Approche temporelle</strong></p>
<ul>
<li>Modèle ARDL USA</li>
<li>Inertie structurelle</li>
<li>Projections 2021-2025</li>
</ul>
<p><strong>Partie IV : Confrontation</strong></p>
<ul>
<li>Convergence des résultats</li>
<li>Hétérogénéité masquée</li>
<li>Implications politiques</li>
</ul>
</div></div>
</section></section>
<section>
<section id="méthodologie" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Méthodologie</h1>

</section>
<section id="nos-trois-choix-méthodologiques-décisifs" class="slide level2 center">
<h2>🔬 Nos trois choix méthodologiques décisifs</h2>
<p><strong>1. Spécification log-log</strong></p>
<ul>
<li class="fragment">Interprétation en <strong>élasticités</strong></li>
<li class="fragment">Validée par Box-Cox (<span class="math inline">\(\lambda = 0.15 \approx 0\)</span>)</li>
<li class="fragment">Formule : <span class="math inline">\(\ln(\text{CO}_2) = f(\ln(\text{PIB}))\)</span></li>
</ul>
<p><strong>2. Test du terme cubique</strong></p>
<p><span class="math display">\[\ln(\text{CO}_2) = \beta_0 + \beta_1 \ln(\text{PIB}) + \beta_2 [\ln(\text{PIB})]^2 + \beta_3 [\ln(\text{PIB})]^3 + \varepsilon\]</span></p>
<ul>
<li class="fragment"><span class="math inline">\(\beta_3 = 0\)</span> → U inversé classique (EKC)</li>
<li class="fragment"><span class="math inline">\(\beta_3 &gt; 0\)</span> → Courbe en N (rebond !)</li>
<li class="fragment"><span class="math inline">\(\beta_3 &lt; 0\)</span> → Déclin accéléré</li>
</ul>
<p><strong>3. Validation prédictive systématique</strong></p>
<ul>
<li class="fragment">Transversal : <strong>k-fold cross-validation</strong> (k=5)</li>
<li class="fragment">Temporel : <strong>test hors-échantillon</strong> (2016-2020)</li>
</ul>
</section>
<section id="modèles-estimés" class="slide level2 center">
<h2>📐 Modèles estimés</h2>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">Approche transversale</a></li><li><a href="#tabset-1-2">Approche temporelle</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p><strong>Modèle polynomial cubique</strong></p>
<p><span class="math display">\[\ln(\text{CO}_2)_i = \beta_0 + \beta_1 \ln(\text{PIB})_i + \beta_2 [\ln(\text{PIB})_i]^2 + \beta_3 [\ln(\text{PIB})_i]^3 + \varepsilon_i\]</span></p>
<p><strong>Estimateur</strong></p>
<ul>
<li><strong>OLS</strong> avec écarts-types robustes <strong>HC3</strong></li>
<li>Correction hétéroscédasticité (N=159 &lt; 250)</li>
</ul>
<p><strong>Validation</strong></p>
<ul>
<li>Cross-validation k=5</li>
<li>Métrique : RMSE moyen</li>
</ul>
</div>
<div id="tabset-1-2">
<p><strong>Modèle ARDL(1,1)</strong></p>
<p><span class="math display">\[\ln(\text{CO}_2)_t = \rho \ln(\text{CO}_2)_{t-1} + \beta_0 \ln(\text{PIB})_t + \beta_1 \ln(\text{PIB})_{t-1} + \varepsilon_t\]</span></p>
<p><strong>Estimateur</strong></p>
<ul>
<li><strong>ARDL</strong> avec écarts-types <strong>Newey-West</strong> (3 lags)</li>
<li>Correction autocorrélation (séries I(1))</li>
</ul>
<p><strong>Validation</strong></p>
<ul>
<li>Split 1990-2015 / 2016-2020</li>
<li>Benchmark : marche aléatoire, ARIMA</li>
</ul>
</div>
</div>
</div>
<aside class="notes">
<p>HC3 est recommandé pour N &lt; 250. Newey-West corrige l’autocorrélation avec un noyau de Bartlett. Le nombre de lags (3) suit la règle <span class="math inline">\(L \approx \lfloor 4(T/100)^{2/9} \rfloor\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="stratégie-de-validation-estimer-et-prédire" class="slide level2 center">
<h2>⚖️ Stratégie de validation : Estimer ET Prédire</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="estimation">🔍 Estimation</h3>
<p><strong>Question</strong> : Quelle relation entre X et Y ?</p>
<p><strong>Critères</strong></p>
<ul>
<li>Significativité (<span class="math inline">\(p &lt; 0.05\)</span>)</li>
<li><span class="math inline">\(R^2\)</span> ajusté</li>
<li>Tests F emboîtés</li>
</ul>
<p><strong>Risque</strong> : Biais de spécification</p>
</div><div class="column" style="width:50%;">
<h3 id="prédiction">🎯 Prédiction</h3>
<p><strong>Question</strong> : Le modèle généralise-t-il ?</p>
<p><strong>Critères</strong></p>
<ul>
<li>RMSE hors-échantillon</li>
<li>Comparaison benchmarks</li>
<li>Stabilité résidus</li>
</ul>
<p><strong>Risque</strong> : Surapprentissage (overfitting)</p>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Principe de parcimonie</strong></p>
</div>
<div class="callout-content">
<p>Un modèle <strong>statistiquement significatif</strong> mais <strong>prédictivement faible</strong> sera rejeté</p>
<p>→ Performance hors-échantillon = arbitre final</p>
</div>
</div>
</div>
</section>
<section id="protocoles-de-validation-détaillés" class="slide level2 center">
<h2>🧪 Protocoles de validation détaillés</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Validation croisée (k=5)</a></li><li><a href="#tabset-2-2">Test hors-échantillon</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p><strong>Principe</strong></p>
<ol type="1">
<li>Partitionner 159 pays en 5 groupes équilibrés</li>
<li>Estimer sur 4/5 des données</li>
<li>Prédire sur 1/5 restant</li>
<li>Répéter 5 fois</li>
<li>Calculer RMSE moyen</li>
</ol>
<p><strong>Pourquoi k=5 ?</strong></p>
<ul>
<li>Compromis biais-variance standard</li>
<li>k=10 donnerait n_train = 143 (trop petit)</li>
</ul>
</div>
<div id="tabset-2-2">
<p><strong>Principe</strong></p>
<ul>
<li><strong>Train</strong> : 1990-2015 (26 obs)</li>
<li><strong>Test</strong> : 2016-2020 (5 obs)</li>
<li>Préserver l’ordre chronologique</li>
</ul>
<p><strong>Benchmarks comparés</strong></p>
<ol type="1">
<li>Marche aléatoire : <span class="math inline">\(y_{t+1} = y_t\)</span></li>
<li>Moyenne mobile : <span class="math inline">\(y_{t+1} = \frac{1}{3}(y_t + y_{t-1} + y_{t-2})\)</span></li>
<li>ARIMA(1,1,1) optimisé</li>
</ol>
</div>
</div>
</div>
</section>
<section id="métriques-de-performance" class="slide level2 center">
<h2>📊 Métriques de performance</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 25%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Métrique</th>
<th>Formule</th>
<th>Interprétation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>RMSE</strong></td>
<td><span class="math inline">\(\sqrt{\frac{1}{n}\sum(y_i - \hat{y}_i)^2}\)</span></td>
<td>Erreur quadratique (pénalise outliers)</td>
</tr>
<tr class="even">
<td><strong>MAE</strong></td>
<td><span class="math inline">\(\frac{1}{n}\sum \|y_i - \hat{y}_i\|\)</span></td>
<td>Erreur absolue (robuste outliers)</td>
</tr>
<tr class="odd">
<td><strong>MAPE</strong></td>
<td><span class="math inline">\(\frac{100}{n}\sum \left\|\frac{y_i - \hat{y}_i}{y_i}\right\|\)</span></td>
<td>Erreur relative (%)</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Métrique principale : RMSE</strong></p>
</div>
<div class="callout-content">
<p>Cohérent avec OLS (minimise la somme des carrés)</p>
<p>→ Pénalise fortement les grosses erreurs (pertinent pour l’action climatique)</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="approche-transversale-1" class="title-slide slide level1 center" data-background-color="#16A085">
<h1>Approche Transversale</h1>

</section>
<section id="photographie-du-monde-en-2020" class="slide level2 center">
<h2>Photographie du monde en 2020</h2>
</section>
<section id="vue-densemble-log-log-vs-log-lin" class="slide level2 center">
<h2>🌍 Vue d’ensemble : Log-log vs Log-lin</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/kuznets_diachronic.png"></p>
<figcaption>Vision du modèle (log-log)</figcaption>
</figure>
</div>
<p><strong>Espace de travail économétrique</strong></p>
<ul>
<li>Variations relatives comparables</li>
<li>Relation relativement linéaire</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/kuznets_diachronic_enhanced.png"></p>
<figcaption>Réalité physique (log-lin)</figcaption>
</figure>
</div>
<p><strong>Réalité climatique en tonnes absolues</strong></p>
<ul>
<li>Dispersion explosive aux hauts revenus</li>
<li>Qatar s’envole, Suède plafonne</li>
</ul>
</div></div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Message clé</strong></p>
</div>
<div class="callout-content">
<p>L’EKC <strong>moyenne</strong> masque des trajectoires <strong>radicalement divergentes</strong></p>
</div>
</div>
</div>
</section>
<section id="résultat-clé-n1-le-modèle-quadratique-suffit" class="slide level2 center">
<h2>📊 Résultat clé n°1 : Le modèle quadratique suffit</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/cross_section_model_2019.png"></p>
<figcaption>Modèle cubique ajusté</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Verdict statistique</strong></p>
</div>
<div class="callout-content">
<p><strong>Le terme cubique est NON significatif</strong></p>
<ul>
<li><span class="math inline">\(\beta_3 = -0.0138\)</span> (p = 0.995)</li>
<li>Test F emboîté : p = 0.994</li>
<li>AIC favorise quadratique (-2 pts)</li>
</ul>
</div>
</div>
</div>
<p><strong>Décision méthodologique</strong></p>
<p>✅ Modèle retenu : <strong>Quadratique</strong></p>
<p>❌ Courbe en N : <strong>rejetée</strong></p>
<p>⚖️ Performance : cubique <strong>dégrade</strong> de +1.4% RMSE</p>
</div></div>
<aside class="notes">
<p>Le terme cubique capture probablement les spécificités de pays rentiers (Qatar, Koweït) plutôt qu’une tendance structurelle. Principe de parcimonie appliqué.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="résultats-de-lestimation-ols" class="slide level2 center">
<h2>📈 Résultats de l’estimation OLS</h2>
<div style="font-size: 0.75em;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Linéaire</th>
<th>Quadratique</th>
<th>Cubique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\ln(\text{PIB})\)</span> centré</td>
<td>1.1000***</td>
<td>1.0698***</td>
<td>1.0703***</td>
</tr>
<tr class="even">
<td></td>
<td>(0.0427)</td>
<td>(0.0431)</td>
<td>(0.0825)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([\ln(\text{PIB})]^2\)</span></td>
<td>—</td>
<td>-0.0832***</td>
<td>-0.0833**</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.0315)</td>
<td>(0.0400)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([\ln(\text{PIB})]^3\)</span></td>
<td>—</td>
<td>—</td>
<td>-0.0002</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td>(0.0268)</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(R^2\)</span> ajusté</strong></td>
<td>0.836</td>
<td>0.842</td>
<td>0.841</td>
</tr>
<tr class="even">
<td><strong>AIC</strong></td>
<td>279.6</td>
<td>274.0</td>
<td>276.0</td>
</tr>
<tr class="odd">
<td><strong>N</strong></td>
<td>159</td>
<td>159</td>
<td>159</td>
</tr>
</tbody>
</table>
</div>
<p><em>Erreurs-types robustes HC3 entre parenthèses. *p&lt;0.1, **p&lt;0.05, ***p&lt;0.01</em></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interprétation</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Modèle quadratique : meilleur compromis <span class="math inline">\(R^2\)</span> / AIC</li>
<li><span class="math inline">\(\beta_2 &lt; 0\)</span> significatif → U inversé validé</li>
<li><span class="math inline">\(\beta_3\)</span> non significatif → pas de rebond détecté</li>
</ul>
</div>
</div>
</div>
</section>
<section id="performance-prédictive-validation-croisée-k5" class="slide level2 center">
<h2>🎯 Performance prédictive : Validation croisée (k=5)</h2>
<div style="text-align: center; font-size: 1.5em; margin: 2em 0;">
<p><strong>RMSE moyen</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Modèle</th>
<th>RMSE</th>
<th>Δ vs quadratique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linéaire</td>
<td>0.5798</td>
<td>+2.0%</td>
</tr>
<tr class="even">
<td><strong>Quadratique</strong></td>
<td><strong>0.5683</strong></td>
<td><strong>référence</strong></td>
</tr>
<tr class="odd">
<td>Cubique</td>
<td>0.5796</td>
<td><strong>-2.0%</strong> ⚠️</td>
</tr>
</tbody>
</table>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interprétation</strong></p>
</div>
<div class="callout-content">
<p>Le modèle cubique <strong>sur-apprend</strong> les données de 2020</p>
<p>→ Quadratique généralise mieux à de nouveaux pays</p>
<p>→ <strong>Parcimonie confirmée</strong></p>
</div>
</div>
</div>
</section>
<section id="diagnostic-des-erreurs-qui-le-modèle-rate-t-il" class="slide level2 center">
<h2>🔍 Diagnostic des erreurs : Qui le modèle rate-t-il ?</h2>

<img data-src="../../artifacts/figures/cross_section_model_2019.png" class="r-stretch quarto-figure-center"><p class="caption">Analyse des erreurs de prédiction</p></section>
<section id="profils-des-pays-mal-prédits" class="slide level2 center">
<h2>🗺️ Profils des pays mal prédits</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🔴 Pays <strong>sous-estimés</strong> (polluent PLUS)</strong></p>
</div>
<div class="callout-content">
<p><strong>30 pays</strong> | PIB moyen : 18 275 $/hab</p>
<p><strong>Profil</strong> : Économies fossiles</p>
<ul>
<li>🛢️ Qatar, Koweït, Bahreïn (rente pétrolière)</li>
<li>⛏️ Australie, Afrique du Sud (exportateurs charbon)</li>
<li>🌡️ Arabie Saoudite (climatisation intensive)</li>
</ul>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>🟢 Pays <strong>surestimés</strong> (polluent MOINS)</strong></p>
</div>
<div class="callout-content">
<p><strong>26 pays</strong> | PIB moyen : 17 398 $/hab</p>
<p><strong>Profil</strong> : Décarbonés volontaristes</p>
<ul>
<li>⚡ France, Suède (nucléaire 70%, hydro 45%)</li>
<li>🌱 Islande, Norvège (100% renouvelables)</li>
<li>🏔️ Suisse (efficacité énergétique)</li>
</ul>
</div>
</div>
</div>
</div></div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Message clé</strong></p>
</div>
<div class="callout-content">
<p>À <strong>PIB égal</strong>, la Suède émet <strong>9 fois moins</strong> que le Qatar</p>
<p>→ Les <strong>choix politiques</strong> comptent plus que la richesse seule</p>
</div>
</div>
</div>
</section>
<section id="bilan-de-lapproche-transversale" class="slide level2 center">
<h2>📝 Bilan de l’approche transversale</h2>
<p>✅ <strong>EKC classique validée</strong> : relation en U inversé confirmée (<span class="math inline">\(\beta_2 &lt; 0\)</span>, p &lt; 0.001)</p>
<p>✅ <strong>Courbe en N rejetée</strong> : pas de rebond aux très hauts revenus (<span class="math inline">\(\beta_3 \approx 0\)</span>, p = 0.995)</p>
<p>✅ <strong>Découplage possible</strong> : les pays riches émettent moins (turning point franchi pour OCDE)</p>
<p>⚠️ <strong>Hétérogénéité masquée</strong> : l’EKC moyenne cache 3 clubs de pays (décarbonés / sur-carbonés / en transition)</p>
<p>❓ <strong>Questions restantes</strong> :</p>
<ul>
<li class="fragment">Ce découplage est-il <strong>durable</strong> dans le temps ?</li>
<li class="fragment">L’<strong>inertie</strong> des systèmes énergétiques permet-elle une transition rapide ?</li>
<li class="fragment">Un pays peut-il <strong>revenir en arrière</strong> après découplage ?</li>
</ul>
<div class="fragment">
<div style="text-align: center; font-size: 1.3em; color: #16A085; margin-top: 1em;">
<p><strong>→ Partie III : Analyse temporelle du cas américain (1990-2020)</strong></p>
</div>
</div>
</section></section>
<section>
<section id="approche-temporelle-1" class="title-slide slide level1 center" data-background-color="#E74C3C">
<h1>Approche Temporelle</h1>

</section>
<section id="le-film-américain-1990-2020" class="slide level2 center">
<h2>Le film américain (1990-2020)</h2>
</section>
<section id="pourquoi-les-états-unis" class="slide level2 center">
<h2>🇺🇸 Pourquoi les États-Unis ?</h2>
<ul>
<li class="fragment">🏭 <strong>Premier émetteur historique cumulé</strong>
<ul>
<li class="fragment">~25% du CO₂ mondial depuis 1850</li>
</ul></li>
<li class="fragment">💰 <strong>Économie mature post-industrielle</strong>
<ul>
<li class="fragment">76 000 $/hab en 2020</li>
<li class="fragment">Services = 77% du PIB</li>
</ul></li>
<li class="fragment">📊 <strong>Données complètes et fiables</strong>
<ul>
<li class="fragment">Série 1990-2020 (T=30)</li>
<li class="fragment">Qualité EPA/NOAA</li>
</ul></li>
<li class="fragment">🎯 <strong>Cas test idéal pour l’EKC</strong>
<ul>
<li class="fragment">Pays ayant théoriquement franchi le turning point</li>
<li class="fragment">Permet d’observer la phase descendante</li>
</ul></li>
</ul>
</section>
<section id="tests-de-stationnarité-adf" class="slide level2 center">
<h2>🧪 Tests de stationnarité (ADF)</h2>
<div style="font-size: 0.85em;">
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 25%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>ADF (niveaux)</th>
<th>p-value</th>
<th>ADF (différences)</th>
<th>p-value</th>
<th>Conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\ln(\text{CO}_2)\)</span></td>
<td>-1.15</td>
<td>0.921</td>
<td>-3.27</td>
<td><strong>0.016</strong></td>
<td><strong>I(1)</strong></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\ln(\text{PIB})\)</span></td>
<td>-1.40</td>
<td>0.860</td>
<td>-2.44</td>
<td>0.132</td>
<td>Ambigu</td>
</tr>
</tbody>
</table>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Diagnostic</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(\ln(\text{CO}_2)\)</span> : clairement <strong>I(1)</strong> (non-stationnaire)</li>
<li><span class="math inline">\(\ln(\text{PIB})\)</span> : résultat <strong>ambigu</strong> (petit échantillon T=30)</li>
</ul>
<p><strong>Causes possibles</strong> : faible puissance du test, break structurel (2008, COVID)</p>
<p><strong>Solution adoptée</strong> : Modèle <strong>ARDL</strong> (robuste aux variables I(0)/I(1) mixtes)</p>
</div>
</div>
</div>
<aside class="notes">
<p>Rappel : H₀ du test ADF = “présence de racine unitaire”. Si p &lt; 0.05, on rejette H₀ → série stationnaire.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modèles-ardl-estimés" class="slide level2 center">
<h2>📐 Modèles ARDL estimés</h2>
<div style="font-size: 0.7em;">
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>AR(1)</th>
<th>ARDL lin.</th>
<th>ARDL quad.</th>
<th>ARDL cub.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\ln(\text{CO}_2)_{t-1}\)</span></td>
<td>1.0523***</td>
<td>1.0032***</td>
<td>1.0974***</td>
<td>1.0324***</td>
</tr>
<tr class="even">
<td></td>
<td>(0.0619)</td>
<td>(0.0779)</td>
<td>(0.0533)</td>
<td>(0.0897)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\ln(\text{PIB})_t\)</span></td>
<td>—</td>
<td>-0.0638*</td>
<td>-0.1223*</td>
<td>-0.1881***</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.0329)</td>
<td>(0.0627)</td>
<td>(0.0493)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([\ln(\text{PIB})_t]^2\)</span></td>
<td>—</td>
<td>—</td>
<td>-0.4220</td>
<td>0.0626</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td>(0.3978)</td>
<td>(0.5913)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\([\ln(\text{PIB})_t]^3\)</span></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>3.5947</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td>(2.2296)</td>
</tr>
<tr class="odd">
<td><strong><span class="math inline">\(R^2\)</span></strong></td>
<td>0.935</td>
<td>0.938</td>
<td>0.939</td>
<td>0.941</td>
</tr>
<tr class="even">
<td><strong>AIC</strong></td>
<td>-121.5</td>
<td>-120.8</td>
<td>-119.3</td>
<td>-118.2</td>
</tr>
</tbody>
</table>
</div>
<p><em>Erreurs-types Newey-West (3 lags). *p&lt;0.1, **p&lt;0.05, ***p&lt;0.01</em></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Observations préliminaires</strong></p>
</div>
<div class="callout-content">
<ul>
<li><span class="math inline">\(R^2\)</span> augmente avec la complexité (0.935 → 0.941)</li>
<li><strong>MAIS</strong> <span class="math inline">\(\beta_3\)</span> non significatif (p = 0.107)</li>
<li>AIC favorise AR(1) (plus parcimonieux)</li>
</ul>
<p>→ Validation hors-échantillon va trancher</p>
</div>
</div>
</div>
</section>
<section id="validation-hors-échantillon-2016-2020" class="slide level2 center">
<h2>🎯 Validation hors-échantillon (2016-2020)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/time_series_usa_forecast.png"></p>
<figcaption>Prédictions hors-échantillon</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div style="font-size: 0.8em;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Modèle</th>
<th>RMSE</th>
<th>MAE</th>
<th>MAPE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>ARDL Linéaire</strong></td>
<td><strong>0.0473</strong></td>
<td>0.0326</td>
<td>3.34</td>
</tr>
<tr class="even">
<td>ARDL AR(1)</td>
<td>0.0474</td>
<td>0.0333</td>
<td>3.41</td>
</tr>
<tr class="odd">
<td>ARDL Quadratique</td>
<td>0.0475</td>
<td>0.0345</td>
<td>3.49</td>
</tr>
<tr class="even">
<td>ARDL Cubique</td>
<td>0.0492</td>
<td>0.0352</td>
<td>3.62</td>
</tr>
<tr class="odd">
<td><strong>Marche aléatoire</strong></td>
<td>0.0568</td>
<td>0.0442</td>
<td>4.57</td>
</tr>
<tr class="even">
<td>ARIMA(1,1,1)</td>
<td>0.0617</td>
<td>0.0414</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Moyenne mobile</td>
<td>0.0682</td>
<td>0.0527</td>
<td>5.51</td>
</tr>
</tbody>
</table>
</div>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Résultat clé n°2</strong></p>
</div>
<div class="callout-content">
<p><strong>ARDL Linéaire</strong> offre la meilleure performance</p>
<ul>
<li>✅ RMSE = 0.0473 (<strong>+18.6%</strong> vs marche aléatoire)</li>
<li>✅ Bat tous les benchmarks</li>
<li>✅ Modèle le plus parcimonieux des ARDL</li>
</ul>
</div>
</div>
</div>
</section>
<section id="décision-de-sélection-de-modèle" class="slide level2 center">
<h2>🤔 Décision de sélection de modèle</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Critère</th>
<th>ARDL Linéaire</th>
<th>ARDL Quadratique</th>
<th>ARDL Cubique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>RMSE Test</strong></td>
<td><strong>0.0473</strong> ✅</td>
<td>0.0475 (+0.5%)</td>
<td>0.0492 (+4.0%) ⚠️</td>
</tr>
<tr class="even">
<td><strong>Coefficient clé</strong></td>
<td>—</td>
<td><span class="math inline">\(\beta_2\)</span> : p=0.289</td>
<td><span class="math inline">\(\beta_3\)</span> : p=0.107</td>
</tr>
<tr class="odd">
<td><strong>Statut</strong></td>
<td>—</td>
<td>Non significatif</td>
<td>Non significatif</td>
</tr>
<tr class="even">
<td><strong>AIC</strong></td>
<td><strong>-120.8</strong> ✅</td>
<td>-119.3</td>
<td>-118.2</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Modèle retenu</strong></p>
</div>
<div class="callout-content">
<p><strong>ARDL Linéaire</strong> pour la performance</p>
<p><strong>ARDL Quadratique</strong> pour l’analyse structurelle (cohérence avec approche transversale)</p>
<p><strong>Verdict sur l’EKC temporelle</strong> : - <span class="math inline">\(\beta_2\)</span> non significatif (p=0.289) → relation <strong>linéaire</strong> sur 1990-2020 - Interprétation : USA déjà dans <strong>phase descendante</strong> de l’EKC - Pas de rebond détecté (<span class="math inline">\(\beta_3\)</span> rejeté)</p>
</div>
</div>
</div>
</section>
<section id="diagnostics-du-modèle-ardl-quadratique" class="slide level2 center">
<h2>📊 Diagnostics du modèle ARDL quadratique</h2>

<img data-src="../../artifacts/figures/time_series_usa_forecast.png" class="r-stretch quarto-figure-center"><p class="caption">Diagnostics résidus</p></section>
<section id="tests-de-spécification" class="slide level2 center">
<h2>✅ Tests de spécification</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Test</th>
<th>Statistique</th>
<th>p-value</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Jarque-Bera</strong> (normalité)</td>
<td>8.35</td>
<td>0.015</td>
<td>⚠️ Non-normalité légère</td>
</tr>
<tr class="even">
<td><strong>Durbin-Watson</strong> (autocorr.)</td>
<td>1.89</td>
<td>—</td>
<td>✅ Pas d’autocorrélation</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interprétation</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✅ Résidus non autocorrélés (DW ≈ 2)</li>
<li>⚠️ Légère déviation de la normalité (acceptable sur T=30)</li>
<li>✅ Pas de pattern systématique exploitable</li>
</ul>
</div>
</div>
</div>
</section>
<section id="résultat-clé-n3-inertie-structurelle-extrême" class="slide level2 center">
<h2>⏱️ Résultat clé n°3 : Inertie structurelle extrême</h2>
<div style="text-align: center; font-size: 2em; margin: 1em 0; color: #E74C3C;">
<p><span class="math inline">\(\rho = 1.003 \approx 1\)</span></p>
</div>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Qu’est-ce que cela signifie concrètement ?</strong></p>
</div>
<div class="callout-content">
<p><strong>Coefficient d’inertie</strong> : <span class="math inline">\(\rho = 1.003\)</span> (proche de la racine unitaire)</p>
<p><strong>Demi-vie</strong> : <span class="math inline">\(H = \frac{\ln(0.5)}{\ln(\rho)}\)</span> → <strong>Non calculable</strong> (diverge mathématiquement)</p>
<p><strong>Interprétation</strong> : Les chocs sur les émissions sont <strong>quasi-permanents</strong></p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Causes structurelles</strong></p>
<ul>
<li>🏭 Centrale charbon → 40 ans</li>
<li>🚗 Flotte automobile → 15 ans</li>
<li>🏘️ Bâtiments → 50+ ans</li>
<li>⚡ Réseau électrique → 30 ans</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Implication politique</strong></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Le découplage <strong>ne s’accélère pas spontanément</strong></p>
<p>Attendre le turning point “naturel” = <strong>stratégie à haut risque climatique</strong></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="élasticités-court-terme-vs-long-terme" class="slide level2 center">
<h2>📉 Élasticités : Court terme vs Long terme</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="court-terme-ct">Court terme (CT)</h3>
<p><span class="math display">\[\varepsilon_{CT} = \beta_0 = -0.122\]</span></p>
<p><strong>Interprétation</strong></p>
<p>+1% de croissance du PIB<br>
→ <strong>-0.12%</strong> d’émissions l’année 1</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Faible élasticité</strong></p>
</div>
<div class="callout-content">
<p>Il faudrait <strong>+8.3%</strong> de croissance annuelle pour réduire les émissions de <strong>1%</strong> par an</p>
<p>→ Rythme insuffisant pour Paris (−7%/an requis)</p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="long-terme-lt">Long terme (LT)</h3>
<p><span class="math display">\[\varepsilon_{LT} = \frac{\beta_0}{1 - \rho}\]</span></p>
<p><strong>Problème</strong></p>
<p>Avec <span class="math inline">\(\rho = 1.003 \geq 1\)</span>, la formule <strong>diverge</strong></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Non calculable</strong></p>
</div>
<div class="callout-content">
<p>Pas d’équilibre de long terme défini</p>
<p><strong>Causes possibles</strong> : - Petit échantillon (T=30) - Instabilité structurelle post-2010 - Processus non-stationnaire</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="turning-point" class="slide level2 center">
<h2>🎯 Turning point</h2>
<div style="text-align: center; font-size: 1.5em; margin: 1.5em 0;">
<p><strong>Turning point : Non calculable</strong> (<span class="math inline">\(\rho \approx 1\)</span> → pas d’équilibre de LT)</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Observation empirique</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/time_series_usa_forecast.png"></p>
<figcaption>Pic USA</figcaption>
</figure>
</div>
<ul>
<li>Pic historique : <strong>~2005-2007</strong></li>
<li>Émissions pic : <strong>~20 t/hab</strong></li>
<li>Baisse depuis : <strong>-30%</strong></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Question de stabilité</strong></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ce déclin est-il durable ?</strong></p>
</div>
<div class="callout-content">
<p><strong>Facteurs de doute</strong> : - COVID-19 (choc temporaire ?) - Délocalisation industrielle - Gaz de schiste (substitution charbon)</p>
<p><strong>Incertitude</strong> : Découplage <strong>structurel</strong> ou <strong>conjoncturel</strong> ?</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="projection-2021-2025" class="slide level2 center">
<h2>🔮 Projection 2021-2025</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../../artifacts/figures/time_series_usa_forecast.png"></p>
<figcaption>Projection avec IC 95%</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Hypothèse</strong> : Croissance PIB <strong>+2%/an</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Année</th>
<th>CO₂ prédit</th>
<th>IC 95%</th>
<th>Δ cumulé</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2021</td>
<td>13.32 t</td>
<td>[12.84 ; 13.83]</td>
<td>-3.6%</td>
</tr>
<tr class="even">
<td>2022</td>
<td>12.78 t</td>
<td>[12.28 ; 13.31]</td>
<td>-7.5%</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>12.19 t</td>
<td>[11.66 ; 12.74]</td>
<td>-11.8%</td>
</tr>
<tr class="even">
<td>2024</td>
<td>11.56 t</td>
<td>[11.00 ; 12.14]</td>
<td>-16.4%</td>
</tr>
<tr class="odd">
<td>2025</td>
<td><strong>10.89 t</strong></td>
<td>[10.30 ; 11.50]</td>
<td><strong>-21.2%</strong></td>
</tr>
</tbody>
</table>
</div></div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>⚠️ Limites de cette projection</strong></p>
</div>
<div class="callout-content">
<ul>
<li>IC s’élargit (+0.6 t en 2025) → incertitude croissante</li>
<li>Scénario <strong>unique</strong> (pas de chocs COVID/politiques)</li>
<li>Stabilité structurelle <strong>supposée</strong> (<span class="math inline">\(\rho &lt; 1\)</span> non garanti)</li>
<li>Pas de rupture technologique modélisée</li>
</ul>
</div>
</div>
</div>
</section>
<section id="bilan-de-lapproche-temporelle" class="slide level2 center">
<h2>📝 Bilan de l’approche temporelle</h2>
<p>✅ <strong>Modèle retenu</strong> : ARDL Quadratique (cohérence transversale) / Linéaire (performance)</p>
<p>✅ <strong>Courbe en N rejetée</strong> : <span class="math inline">\(\beta_3\)</span> non significatif (p = 0.107)</p>
<p>⚠️ <strong>Inertie extrême</strong> : <span class="math inline">\(\rho = 1.003 \approx 1\)</span> → demi-vie non calculable</p>
<p>⚠️ <strong>Découplage lent</strong> : <span class="math inline">\(\varepsilon_{CT} = -0.12\)</span> (faible élasticité)</p>
<p>📉 <strong>Projection 2025</strong> : -21.2% vs 2020 (mais loin des -50% requis pour Paris)</p>
<p>❓ <strong>Question centrale</strong> : Découplage <strong>structurel</strong> ou <strong>conjoncturel</strong> ?</p>
<div class="fragment">
<div style="text-align: center; font-size: 1.3em; color: #E74C3C; margin-top: 1em;">
<p><strong>→ Partie IV : Confrontation des deux approches</strong></p>
</div>
</div>
</section></section>
<section>
<section id="confrontation-et-conclusion" class="title-slide slide level1 center" data-background-color="#34495E">
<h1>Confrontation et Conclusion</h1>

</section>
<section id="convergence-les-deux-approches-saccordent" class="slide level2 center">
<h2>🔄 Convergence : Les deux approches s’accordent</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Validation de l’EKC classique (U inversé)</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 28%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Approche</th>
<th><span class="math inline">\(\beta_3\)</span></th>
<th>p-value</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>📸 Transversale (159 pays, 2020)</td>
<td>-0.0002</td>
<td>0.995</td>
<td>Non significatif</td>
</tr>
<tr class="even">
<td>🎬 Temporelle (USA, 1990-2020)</td>
<td>0.4421</td>
<td>0.387</td>
<td>Non significatif</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Points de convergence</strong></p>
<p>✅ <strong>Forme fonctionnelle</strong> : Modèle <strong>quadratique</strong> suffisant</p>
<p>✅ <strong>Courbe en N rejetée</strong> : Pas de rebond aux très hauts revenus (<span class="math inline">\(\beta_3 \approx 0\)</span>)</p>
<p>✅ <strong>Découplage réel</strong> : Les pays riches émettent moins</p>
<p>✅ <strong>Robustesse méthodologique</strong> : Cohérence espace-temps</p>
</section>
<section id="divergence-vitesse-vs-hétérogénéité" class="slide level2 center">
<h2>⚡ Divergence : Vitesse vs Hétérogénéité</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="vision-transversale">📸 Vision transversale</h3>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Message</strong> : Découplage <strong>possible</strong></p>
<ul>
<li>Les pays riches émettent <strong>moins</strong> que les pauvres</li>
<li><span class="math inline">\(\beta_2 &lt; 0\)</span> hautement significatif</li>
<li>Turning point <strong>franchi</strong> pour l’OCDE</li>
</ul>
<p><strong>Mais…</strong> - Photographie <strong>statique</strong> - Masque l’<strong>hétérogénéité</strong> massive</p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="vision-temporelle">🎬 Vision temporelle</h3>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Message</strong> : Découplage <strong>lent</strong></p>
<ul>
<li><span class="math inline">\(\rho \approx 1\)</span> (<strong>inertie extrême</strong>)</li>
<li><span class="math inline">\(\varepsilon_{CT} = -0.12\)</span> (<strong>faible</strong> élasticité)</li>
<li>Demi-vie <strong>non calculable</strong></li>
</ul>
<p><strong>Donc…</strong> - Transition <strong>graduelle</strong> (30+ ans) - <strong>Non spontanée</strong> (politiques requises)</p>
</div>
</div>
</div>
</div></div>
<div style="margin-top: 1em;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Synthèse</strong></p>
</div>
<div class="callout-content">
<p><strong>L’EKC décrit une tendance conditionnelle, pas une loi automatique</strong></p>
<p>Le découplage <strong>existe</strong>, mais il est <strong>hétérogène</strong>, <strong>lent</strong>, et <strong>non garanti</strong> sans politiques volontaristes</p>
</div>
</div>
</div>
</div>
</section>
<section id="lhétérogénéité-cachée-trois-clubs-de-pays" class="slide level2 center">
<h2>🌍 L’hétérogénéité cachée : Trois clubs de pays</h2>
<div style="font-size: 0.8em;">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 29%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Profil</th>
<th>Exemples</th>
<th>Position vs EKC</th>
<th>Caractéristique clé</th>
<th>Turning point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>🟢 <strong>Décarbonés</strong></td>
<td>France, Suède, Suisse</td>
<td><strong>Sous</strong> la courbe</td>
<td>Mix bas-carbone (nucléaire, hydro)</td>
<td>Atteint ~1990-2000</td>
</tr>
<tr class="even">
<td>🔴 <strong>Sur-carbonés</strong></td>
<td>Qatar, Koweït, Australie</td>
<td><strong>Au-dessus</strong></td>
<td>Rente fossile, climat extrême</td>
<td>Faible découplage</td>
</tr>
<tr class="odd">
<td>🟡 <strong>En transition</strong></td>
<td>Chine, Inde, Brésil</td>
<td><strong>Sur</strong> la courbe</td>
<td>Industrialisation en cours</td>
<td>Pas encore atteint</td>
</tr>
</tbody>
</table>
</div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>📊 Exemple frappant : Suède vs Qatar</strong></p>
</div>
<div class="callout-content">
<p>À <strong>PIB comparable</strong> (~50 000 $/hab) :</p>
<ul>
<li>🇸🇪 Suède : <strong>4 t CO₂/hab</strong> (hydro 45%, nucléaire 30%, taxe carbone depuis 1991)</li>
<li>🇶🇦 Qatar : <strong>35 t CO₂/hab</strong> (gaz 100%, subventions fossiles, climatisation intensive)</li>
</ul>
<p><strong>Facteur 9</strong> de différence → <strong>Les politiques comptent plus que la richesse</strong></p>
</div>
</div>
</div>
</section>
<section id="le-tunneling-sauter-lindustrialisation-fossile" class="slide level2 center">
<h2>🚇 Le “Tunneling” : Sauter l’industrialisation fossile ?</h2>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Concept de Munasinghe (1999)</strong></p>
</div>
<div class="callout-content">
<p><strong>Question</strong> : Les pays en développement peuvent-ils éviter le pic d’émissions des pays riches ?</p>
<p><strong>Idée</strong> : “Creuser un tunnel” sous la courbe EKC via adoption directe de technologies propres</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Conditions de réussite</strong></p>
<ul>
<li class="fragment">✅ Transferts technologiques Nord-Sud</li>
<li class="fragment">✅ Financement climatique (100 Md$/an COP15)</li>
<li class="fragment">✅ Prix du carbone international</li>
<li class="fragment">✅ Sauts technologiques (leapfrogging)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Exemples prometteurs</strong></p>
<ul>
<li>🇰🇪 <strong>Kenya</strong> : 90% électricité géothermie</li>
<li>🇨🇳 <strong>Chine</strong> : leader solaire mondial (70% production PV)</li>
<li>🇮🇳 <strong>Inde</strong> : 500 GW renouvelables visés (2030)</li>
<li>🇧🇩 <strong>Bangladesh</strong> : 6M foyers solaires off-grid</li>
</ul>
</div></div>
</section>
<section id="le-verdict-des-données" class="slide level2 center">
<h2>📊 Le verdict des données</h2>
<div style="font-size: 1.1em;">
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Réponse à la question initiale</strong></p>
</div>
<div class="callout-content">
<blockquote>
<p><strong>« La croissance économique finit-elle par réduire la pollution ? »</strong></p>
</blockquote>
<h3 id="oui-mais">✅ OUI… <strong>MAIS</strong></h3>
</div>
</div>
</div>
</div>
<p><strong>1. Validation statistique</strong></p>
<ul>
<li class="fragment">L’EKC classique (U inversé) est <strong>confirmée</strong> en moyenne</li>
<li class="fragment">Découplage <strong>réel</strong> dans les pays OCDE (phase descendante observable)</li>
<li class="fragment">Courbe en N (rebond) <strong>rejetée</strong> empiriquement</li>
</ul>
<p><strong>2. Hétérogénéité structurelle masquée</strong></p>
<ul>
<li class="fragment">L’EKC <strong>moyenne</strong> cache <strong>3 clubs</strong> de trajectoires opposées</li>
<li class="fragment">À PIB égal : <strong>facteur 9</strong> de différence d’émissions (Suède vs Qatar)</li>
<li class="fragment">Les <strong>politiques</strong> comptent plus que la richesse seule</li>
</ul>
<p><strong>3. Le découplage n’est pas automatique</strong></p>
<ul>
<li class="fragment"><strong>Inertie extrême</strong> : <span class="math inline">\(\rho \approx 1\)</span> → chocs quasi-permanents</li>
<li class="fragment"><strong>Transition lente</strong> : USA -21% projeté (2025) ≠ -50% requis (Paris)</li>
<li class="fragment"><strong>Non spontané</strong> : Politiques volontaristes <strong>indispensables</strong></li>
</ul>
</section>
<section id="implications-pour-laction-climatique" class="slide level2 center">
<h2>💡 Implications pour l’action climatique</h2>
<div style="font-size: 0.9em;">
<p><strong>1. Ne pas compter sur le marché seul</strong></p>
<ul>
<li class="fragment">L’EKC n’est <strong>pas automatique</strong> (cf.&nbsp;Qatar vs Suède)</li>
<li class="fragment">Instruments requis : taxe carbone, normes, investissements publics, R&amp;D</li>
</ul>
<p><strong>2. Anticiper l’inertie structurelle</strong></p>
<ul>
<li class="fragment">Demi-vie ~5+ ans → politiques <strong>durables</strong> nécessaires (pas de stop-and-go)</li>
<li class="fragment">Verrouillage infrastructures → agir <strong>maintenant</strong> (chaque année compte)</li>
<li class="fragment">Lock-in technologique → planifier <strong>30 ans</strong> à l’avance</li>
</ul>
<p><strong>3. Trajectoire USA trop lente pour Net Zero 2050</strong></p>
<ul>
<li class="fragment">Projection 2025 : -21% ≠ objectif -50% (Accord de Paris)</li>
<li class="fragment">Besoin de <strong>rupture</strong> : Green New Deal, tarification carbone, électrification massive</li>
<li class="fragment">Transition graduelle <strong>incompatible</strong> avec budget carbone 1.5°C</li>
</ul>
<p><strong>4. Opportunité du tunneling pour les pays du Sud</strong></p>
<ul>
<li class="fragment">Éviter le pic d’émissions des pays industrialisés</li>
<li class="fragment">Transferts technologiques <strong>essentiels</strong> (Article 10 Accord de Paris)</li>
<li class="fragment">Financement climatique à <strong>l’échelle</strong> (COP28 : Loss &amp; Damage Fund)</li>
</ul>
</div>
</section>
<section id="limites-et-extensions-futures" class="slide level2 center">
<h2>🔍 Limites et extensions futures</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="limites-identifiées">⚠️ Limites identifiées</h3>
<p><strong>Données</strong> - Émissions <strong>territoriales</strong> (biais pollution haven) - Agrégation <strong>nationale</strong> (disparités régionales)</p>
<p><strong>Méthodologie</strong> - Variables <strong>omises</strong> (mix énergétique, institutions) - Cointégration <strong>non testée</strong> (ECM possible) - Projection <strong>mono-scénario</strong> - IC probablement <strong>sous-estimés</strong> (<span class="math inline">\(\rho \approx 1\)</span>)</p>
<p><strong>Généralisation</strong> - Cas USA <strong>non généralisable</strong> aux émergents - Période <strong>1990-2020</strong> (manque recul post-COVID)</p>
</div><div class="column" style="width:50%;">
<h3 id="extensions-envisagées">🔬 Extensions envisagées</h3>
<p><strong>Court terme</strong> - Validation <strong>ex-post</strong> 2021-2023 (données IEA disponibles) - Scénarios <strong>multiples</strong> (SSP1-5 du GIEC) - Test <strong>KPSS</strong> (stationnarité alternative)</p>
<p><strong>Moyen terme</strong> - <strong>Panel multi-pays</strong> (effets fixes, GMM) - Test de <strong>cointégration</strong> formelle (Johansen, ARDL bounds test) - Variables de <strong>contrôle</strong> (mix énergétique, qualité institutions)</p>
<p><strong>Long terme</strong> - Modèles à <strong>seuil</strong> (regime-switching) - <strong>Machine learning</strong> (Random Forest, XGBoost) - Analyse de <strong>sensibilité</strong> formelle (variables omises)</p>
</div></div>
</section>
<section id="message-à-retenir" class="slide level2 center">
<h2>📚 Message à retenir</h2>
<div style="text-align: center; font-size: 1.5em; margin: 2em 0; color: #2C3E50;">
<p><strong>« Le marché ne sauvera pas le climat.</strong></p>
<p><strong>Seules des politiques publiques ciblées, durables et ambitieuses le feront. »</strong></p>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Trois enseignements clés</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><p><strong>L’EKC existe</strong> → mais elle est <strong>conditionnelle</strong>, pas automatique</p></li>
<li><p><strong>L’inertie est réelle</strong> → chaque année de retard verrouille des émissions futures</p></li>
<li><p><strong>Les politiques sont décisives</strong> → Suède vs Qatar le prouve empiriquement</p></li>
</ol>
</div>
</div>
</div>
</section>
<section class="slide level2 center">

</section></section>
<section>
<section id="merci" class="title-slide slide level1 center" data-background-color="#16A085">
<h1>Merci</h1>

</section>
<section id="questions" class="slide level2 center">
<h2>Questions ?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Contacts</strong></p>
<ul>
<li>📧 morphion.research@univ.fr</li>
<li>🔗 <a href="https://github.com">github.com/morphion/kuznets-co2</a></li>
<li>📄 Rapport complet (PDF 51 pages)</li>
</ul>
<p><strong>Ressources</strong></p>
<ul>
<li>💻 Code source (Python + Quarto)</li>
<li>📊 Données (OWID harmonisées)</li>
<li>📓 Notebooks reproductibles</li>
<li>🔬 Tests statistiques détaillés</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Questions anticipées</strong></p>
</div>
<div class="callout-content">
<p><strong>“Pourquoi avoir écarté le cubique ?”</strong> → Performance prédictive prime sur significativité statistique (parcimonie)</p>
<p><strong>“Variables omises (mix énergétique) ?”</strong> → Oui, limite assumée. Extension future avec contrôles</p>
<p><strong>“Projection post-COVID ?”</strong> → Non modélisé (scénario tendanciel, pas de chocs)</p>
<p><strong>“Pourquoi les USA ?”</strong> → Données longues (T=30), économie mature, cas test EKC idéal</p>
<p><strong>“Biais pollution haven ?”</strong> → Reconnu. Empreinte carbone (imports-exports) serait meilleure mais moins de données</p>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="annexes" class="title-slide slide level1 center" data-background-color="#7F8C8D">
<h1>Annexes</h1>

</section>
<section id="a1.-statistiques-descriptives" class="slide level2 center">
<h2>📊 A1. Statistiques descriptives</h2>
<div style="font-size: 0.8em;">
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Moyenne</th>
<th>Écart-type</th>
<th>Min</th>
<th>Q1</th>
<th>Médiane</th>
<th>Q3</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CO₂/hab (t)</td>
<td>4.95</td>
<td>5.12</td>
<td>0.03</td>
<td>1.21</td>
<td>3.08</td>
<td>6.89</td>
<td>37.29</td>
</tr>
<tr class="even">
<td>PIB/hab ($)</td>
<td>18,473</td>
<td>20,115</td>
<td>661</td>
<td>3,892</td>
<td>11,045</td>
<td>26,384</td>
<td>116,935</td>
</tr>
<tr class="odd">
<td>ln(CO₂)</td>
<td>1.18</td>
<td>1.23</td>
<td>-3.51</td>
<td>0.19</td>
<td>1.13</td>
<td>1.93</td>
<td>3.62</td>
</tr>
<tr class="even">
<td>ln(PIB)</td>
<td>9.41</td>
<td>1.35</td>
<td>6.49</td>
<td>8.27</td>
<td>9.31</td>
<td>10.18</td>
<td>11.67</td>
</tr>
</tbody>
</table>
</div>
<p><strong>Échantillon</strong> : 159 pays, année 2020</p>
</section>
<section id="a2.-formules-des-estimateurs" class="slide level2 center">
<h2>🧮 A2. Formules des estimateurs</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1">OLS</a></li><li><a href="#tabset-3-2">Newey-West</a></li><li><a href="#tabset-3-3">ARDL</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p><strong>Estimateur</strong></p>
<p><span class="math display">\[\hat{\beta} = (X'X)^{-1}X'Y\]</span></p>
<p><strong>Variance HC3</strong></p>
<p><span class="math display">\[\widehat{\text{Var}}_{HC3}(\hat{\beta}) = (X'X)^{-1} \left(\sum_{i=1}^n \frac{\hat{\varepsilon}_i^2}{(1-h_{ii})^2} x_i x_i'\right) (X'X)^{-1}\]</span></p>
<p>où <span class="math inline">\(h_{ii}\)</span> = levier de l’observation <span class="math inline">\(i\)</span></p>
</div>
<div id="tabset-3-2">
<p><strong>Variance HAC</strong></p>
<p><span class="math display">\[\widehat{\text{Var}}_{NW}(\hat{\beta}) = (X'X)^{-1} \hat{\Omega} (X'X)^{-1}\]</span></p>
<p>avec</p>
<p><span class="math display">\[\hat{\Omega} = \hat{\Gamma}_0 + \sum_{j=1}^L \left(1 - \frac{j}{L+1}\right) (\hat{\Gamma}_j + \hat{\Gamma}_j')\]</span></p>
<p><strong>Choix de L</strong> : <span class="math inline">\(L \approx \lfloor 4(T/100)^{2/9} \rfloor\)</span> → L=3 pour T=30</p>
</div>
<div id="tabset-3-3">
<p><strong>Spécification ARDL(1,1)</strong></p>
<p><span class="math display">\[Y_t = \rho Y_{t-1} + \beta_0 X_t + \beta_1 X_{t-1} + \varepsilon_t\]</span></p>
<p><strong>Paramètres structurels</strong></p>
<ul>
<li>Élasticité CT : <span class="math inline">\(\varepsilon_{CT} = \beta_0\)</span></li>
<li>Élasticité LT : <span class="math inline">\(\varepsilon_{LT} = \frac{\beta_0 + \beta_1}{1 - \rho}\)</span> (si <span class="math inline">\(|\rho| &lt; 1\)</span>)</li>
<li>Demi-vie : <span class="math inline">\(H = \frac{\ln(0.5)}{\ln(\rho)}\)</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="a3.-tests-de-spécification" class="slide level2 center">
<h2>📉 A3. Tests de spécification</h2>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Test ADF</a></li><li><a href="#tabset-4-2">Test F emboîté</a></li><li><a href="#tabset-4-3">AIC</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
<p><strong>Régression auxiliaire</strong></p>
<p><span class="math display">\[\Delta y_t = \alpha + \beta t + \gamma y_{t-1} + \sum_{i=1}^p \delta_i \Delta y_{t-i} + \varepsilon_t\]</span></p>
<p><strong>Hypothèses</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span> : <span class="math inline">\(\gamma = 0\)</span> (racine unitaire → non-stationnaire)</li>
<li><span class="math inline">\(H_1\)</span> : <span class="math inline">\(\gamma &lt; 0\)</span> (stationnaire)</li>
</ul>
<p><strong>Règle</strong> : Si stat. t &lt; valeur critique (ou p &lt; 0.05) → rejeter <span class="math inline">\(H_0\)</span></p>
</div>
<div id="tabset-4-2">
<p><strong>Statistique</strong></p>
<p><span class="math display">\[F = \frac{(SSR_r - SSR_u)/q}{SSR_u/(n-k-1)} \sim F(q, n-k-1)\]</span></p>
<p>où : - <span class="math inline">\(SSR_r\)</span> = somme carrés résidus (modèle contraint) - <span class="math inline">\(SSR_u\)</span> = somme carrés résidus (modèle non-contraint) - <span class="math inline">\(q\)</span> = nombre de contraintes</p>
</div>
<div id="tabset-4-3">
<p><strong>Formule</strong></p>
<p><span class="math display">\[AIC = 2k - 2\ln(\hat{L})\]</span></p>
<p>où : - <span class="math inline">\(k\)</span> = nombre de paramètres - <span class="math inline">\(\hat{L}\)</span> = vraisemblance maximale</p>
<p><strong>Interprétation</strong> : Plus bas = meilleur (pénalise la complexité)</p>
</div>
</div>
</div>
</section>
<section id="a4.-validation-box-cox" class="slide level2 center">
<h2>🔬 A4. Validation Box-Cox</h2>
<p><strong>Principe</strong> : Déterminer la transformation optimale de <span class="math inline">\(Y\)</span></p>
<p><span class="math display">\[Y^{(\lambda)} = \begin{cases}
\frac{Y^\lambda - 1}{\lambda} &amp; \text{si } \lambda \neq 0 \\
\ln(Y) &amp; \text{si } \lambda = 0
\end{cases}\]</span></p>
<p><strong>Résultats</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Paramètre</th>
<th>Valeur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\lambda\)</span> optimal</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Distance à log (<span class="math inline">\(\lambda=0\)</span>)</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>Distance à linéaire (<span class="math inline">\(\lambda=1\)</span>)</td>
<td>0.85</td>
</tr>
</tbody>
</table>
<p><strong>Conclusion</strong> : Transformation <strong>logarithmique</strong> fortement justifiée</p>
</section>
<section id="a5.-validation-non-paramétrique-lowess" class="slide level2 center">
<h2>📐 A5. Validation non-paramétrique (LOWESS)</h2>

<img data-src="../../artifacts/figures/kuznets_diachronic_enhanced.png" class="r-stretch quarto-figure-center"><p class="caption">Modèles paramétriques vs LOWESS</p><p><strong>Objectif</strong> : Vérifier que la forme quadratique n’est pas trop restrictive</p>
<p><strong>Méthode</strong> : LOWESS (Locally Weighted Scatterplot Smoothing)</p>
<p><strong>Résultat</strong> : Le modèle quadratique <strong>suit bien</strong> la tendance LOWESS</p>
</section>
<section id="a6.-carte-des-résidus-facultatif" class="slide level2 center">
<h2>🌍 A6. Carte des résidus (facultatif)</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Extension possible</strong></p>
</div>
<div class="callout-content">
<p>Visualisation géographique des pays sur/sous-estimés par l’EKC</p>
<p><strong>Outils</strong> : <code>plotly</code>, <code>geopandas</code></p>
</div>
</div>
</div>
</section>
<section id="références-clés" class="slide level2 center">
<h2>📚 Références clés</h2>
<div style="font-size: 0.75em;">
<p><strong>Fondations théoriques</strong> - Grossman, G. M., &amp; Krueger, A. B. (1995). <em>Economic Growth and the Environment</em>. QJE. - Stern, D. I. (2004). <em>The Rise and Fall of the Environmental Kuznets Curve</em>. World Development.</p>
<p><strong>Critiques méthodologiques</strong> - Wagner, M. (2008). <em>The Carbon Kuznets Curve: A Cloudy Picture Emitted by Bad Econometrics?</em>. Resource and Energy Economics. - Peters, G. P., et al.&nbsp;(2011). <em>Growth in emission transfers via international trade</em>. PNAS.</p>
<p><strong>Extensions récentes</strong> - Allard, A., et al.&nbsp;(2018). <em>The N-shaped environmental Kuznets curve</em>. Economics Letters.</p>
<p><strong>Méthodes économétriques</strong> - Pesaran, M. H., et al.&nbsp;(2001). <em>Bounds testing approaches to the analysis of level relationships</em>. Journal of Applied Econometrics. - Newey, W. K., &amp; West, K. D. (1987). <em>A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix</em>. Econometrica.</p>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"right","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"width":"wide","items":[{"text":"Accueil","href":"index.html"}]},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 2000,

        height: 1300,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>